language: generic

# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

# prepare the machine before any code
# installation scripts
# before_install:
#   - './.travis/main.sh'

jobs:
  include:
    - stage: build docker image
# first execute the test suite.
# after the test execution is done and didn't
# fail, build the images (if this step fails
# the whole Travis build is considered a failure).

      script:
      - docker build -t curtesmith/my-hello-world:latest .
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - docker push curtesmith/my-hello-world:latest

    - stage: create the infrastructure
      script:
      - echo "build the infrastructure here"

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# after_success:

# don't notify me when things fail
notifications:
  email: false
