language: generic

# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

# prepare the machine before any code
# installation scripts
# before_install:
#   - './.travis/main.sh'

jobs:
  include:
    - stage: "docker build"
# first execute the test suite.
# after the test execution is done and didn't
# fail, build the images (if this step fails
# the whole Travis build is considered a failure).
script:
# - 'make test'
# - 'make image'
  - docker build -t curtesmith/my-hello-world:latest .

  - stage: "docker push"
script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push curtesmith/my-hello-world:latest ;
    fi

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# after_success:

# don't notify me when things fail
notifications:
  email: false
