version: '3.7'

services:

  sample:
    container_name: my-hello-world
    image: my-hello-world:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3001:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true